src/Entity/Game.php
<?php

namespace App\Entity;

use App\Common\Traits\String\SlugifyTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\GameRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Game
{
    use SlugifyTrait;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $category;

    /**
     * @ORM\Column(type="text", nullable=false)
     * @Assert\NotBlank()
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     * @Assert\NotBlank()
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $img;

    /**
     * @Gedmo\Slug(fields={"name"})
     * @ORM\Column(length=128, unique=true)
     */
    private $slug;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Club", inversedBy="games")
     * @ORM\JoinTable(name="club_game")
     * @ORM\JoinColumn(nullable=false)
     */
    private $clubs;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Matche", mappedBy="game")
     */
    private $matches;

    public function __construct()
    {
        $this->clubs = new ArrayCollection();
        $this->matches = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->name;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param mixed $description
     */
    public function setDescription($description): void
    {
        $this->description = $description;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getImg()
    {
        return $this->img;
    }

    /**
     * @param mixed $img
     */
    public function setImg($img)
    {
        $this->img = $img;
    }

    /**
     * @return mixed
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * @param mixed $slug
     */
    public function setSlug($slug): void
    {
        $this->slug = $slug;
    }

    /**
     * @return mixed
     */
    public function getMatch()
    {
        return $this->matches;
    }

    /**
     * @param Matche $matche
     */
    public function addMatch($matche)
    {
        $this->matches[] = $matche;
    }

    /**
     * @param Matche $matche
     * @return $this
     */
    public function removeMatch($matche)
    {
        $this->matches->removeElement($matche);

        return $this;
    }

    /**
     * @return mixed
     */
    public function getClubs()
    {
        return $this->clubs;
    }

    /**
     * @param $club
     */
    public function addClubs($club): void
    {
        $this->clubs = $club;
    }

    /**
     * @param $club
     * @return $this
     */
    public function removeClub($club)
    {
        $this->clubs->removeElement($club);

        return $this;
    }

    public function addSlugToImageName()
    {
        return $this->slugify($this->name);
    }

}

src/Form/GameType.php
<?php

namespace App\Form;

use App\Entity\Club;
use App\Entity\Game;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class GameType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'game.name',
                'required' => true,
                'translation_domain' => 'game',
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'game.name'
                ]])
            ->add('category', TextType::class, [
                'label' => 'game.category',
                'required' => true,
                'translation_domain' => 'game',
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'game.category'
                ]])
            ->add('description', TextareaType::class, [
                'label' => 'game.description',
                'required' => false,
                'translation_domain' => 'game',
                'attr' => [
                    'class' => 'form-control'
                ]])
            ->add('price', MoneyType::class, [
                'label' => 'game.price',
                'required' => true,
                'translation_domain' => 'game',
                'attr' => [
                    'class' => 'form-control',
                    'id' => "addDollarSignHere",
                    'ext' => "100.00",
                    'placeholder' => 'game.price'
                ]])
            ->add('img', FileType::class, [
                'data_class' => null,
                'label' => 'game.img',
                'required' => false,
                'translation_domain' => 'game',
                'attr' => [
                    'class' => 'form-control dropify',
                    'placeholder' => 'game.img'
                ]])
            ->add('clubs', EntityType::class, [
                'class' => Club::class,
                'label' => 'game.establishment',
                'required' => true,
                'translation_domain' => 'game',
                'multiple' => true,
                'attr' => [
                    'class' => 'form-control'
                ]]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Game::class,
        ]);
    }
}

src/Controller/ShiniGami/GameController.php
<?php

namespace App\Controller\ShiniGami;

use App\Entity\Game;
use App\Form\GameType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Asset\Package;
use Symfony\Component\Asset\Packages;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class GameController
 * @package App\Controller\Game
 */
class GameController extends Controller
{

    /**
     * Show games list
     *
     * @Route(
     *     path="/game",
     *     name="index_game"
     *      )
     * @Method({"GET", "POST"})     *
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();
        $games = $em->getRepository(Game::class)->findAll();
        // We want just to be able delete the games that haven't matches :
        //$gamesHaveNotMatches = $em->getRepository(Game::class)->findGamesHaveNotMatches();
        return $this->render("game/index.html.twig", [
            "games" => $games
        ]);
    }

    /**
     * @Route("/game/show-game/{slug}", name="show_game")
     * @ParamConverter("game", options={"mapping": {"slug": "slug"}})
     * @param Game $game
     * @return Response
     */
    public function showAction(Game $game)
    {
        return $this->render("game/show_game.html.twig", [
            "game" => $game
        ]);
    }

    /**
     * Add a new game
     *
     * @Route(path="/game/add-game", name="add_game")
     * @param Request $request
     * @return Response
     * @Security("has_role('ROLE_ADMIN')")
     */
    public function addAction(Request $request)
    {
        $game = new Game();
        $form = $this->createForm(GameType::class, $game);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $img = $game->getImg();

            if(null !== $img){

                $fileName = $game->addSlugToImageName() . '.' . $img->guessExtension();
                $img->move(
                    $this->getParameter('game_assets_dir'),
                    $fileName
                );
                $game->setImg($fileName);
            }

            $em->persist($game);
            $em->flush();


            return $this->redirectToRoute("index_game");
        }
        return $this->render("game/add_game.html.twig", [
            "form" => $form->createView()
        ]);
    }

    /**
     * Update an game
     *
     * @Route(path="/game/edit-game/{id}", name="edit_game")
     * @param Request $request
     * @param Game $game
     * @param Packages $asset
     * @return Response
     * @Security("has_role('ROLE_ADMIN')")
     */
    public function updateAction(Request $request, Game $game, Packages $asset)
    {
        $form = $this->createForm(GameType::class, $game);
        $form->add('img', FileType::class, [
            'data_class' => null,
            'attr' =>[
                'data-default-file' => $asset->getUrl('images/game/'.$game->getImg()),
                'class' => 'form-control dropify',
            ]
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $image = $game->getImg();
            # Only if image exist
            if ($image) {
                $fileName = $game->addSlugToImageName() . '.' . $image->guessExtension();

                # move uploaded file
                $image->move(
                    $this->getParameter('game_assets_dir'),
                    $fileName
                );

                $game->setImg($fileName);
            } else {
                # restore original image if not modified
                $game->setImg($image);
            }

            $em = $this->getDoctrine()->getManager();
            $em->persist($game);
            $em->flush();

            return $this->redirectToRoute("index_game");
        }

        return $this->render("game/add_game.html.twig", [
            "form" => $form->createView(),
            "id"   => $game->getId()
        ]);
    }

    /**
     * Delete an game
     *
     * @Route(path="/game/delete-game/{id}", name="delete_game")
     * @param Request $request
     * @param Game $game
     * @Method("POST")
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     * @Security("has_role('ROLE_ADMIN')")
     */
    public function deleteAction(Request $request, Game $game)
    {
        if (!$this->isCsrfTokenValid('delete', $request->request->get('token'))) {
            return $this->redirectToRoute("index_game");
        }
        $gameName = $game->getName();

        $em = $this->getDoctrine()->getManager();
        $em->remove($game);
        $em->flush();

        $this->addFlash('info', "Le jeu $gameName a bien été supprimé.");

        return $this->redirectToRoute('index_game');
    }
}

templates/game/add_game.html.twig
{% extends 'layout.html.twig' %}

{% trans_default_domain 'game' %}

{% set active = 'game' %}
{% set addMatch = path('add_game') %}
{% if id is defined %}
    {% set editMatch = path('edit_game', {'id':id}) %}
{% endif %}
{% set currentPath = path(app.request.get('_route'), app.request.attributes.get('_route_params'))  %}
{% block page_title %}
    {{ 'game.add.game' | trans }}
{% endblock %}

{% block content %}

    <div class="form">
        
        {{ form_start(form) }}

        <div class="field-wrap">
            {{ form_row(form.name) }}
        </div>
        {{ form_widget(form) }}

        {% if currentPath == addMatch %}
            <button type="submit" value="submit" class="button button-block">{{ 'game.add' | trans }}</button>
        {% elseif currentPath == editMatch %}
            <button type="submit" value="submit" class="button button-block">{{ 'game.edit' | trans }}</button>
        {% endif %}
        
    </div>

    {{ form_end(form) }}

{% endblock %}



{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/css/dropify.min.css" integrity="sha256-AWdeVMUYtwLH09F6ZHxNgvJI37p+te8hJuSMo44NVm0=" crossorigin="anonymous" />
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="https://cdn.ckeditor.com/4.8.0/standard/ckeditor.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/js/dropify.min.js" integrity="sha256-SUaao5Q7ifr2twwET0iyXVy0OVnuFJhGVi5E/dqEiLU=" crossorigin="anonymous"></script>
    <script>
        CKEDITOR.replace( 'game_description' );
        $('.dropify').dropify({
            messages: {
                default: 'Glissez-d&eacute;posez un fichier ici ou cliquez',
                replace: 'Glissez-d&eacute;posez un fichier ou cliquez pour remplacer',
                remove:  'Supprimer',
                error:   'D&eacute;sol&eacute;, le fichier est trop volumineux'
            }
        });
    </script>
{% endblock %}

templates/game/index.html.twig
{% extends 'layout.html.twig' %}

{% trans_default_domain 'game' %}

{% set active = 'games' %}

{% block page_title %}
    {{ 'game.list' | trans }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href={{ asset("css/style_list.css") }}>
    <style media="print">
        table td {
            vertical-align: middle;
            background: #ffffff;
            border: 2px solid gray;
            border-right: 0;
            box-shadow: 0px 0px 0px 0px #eaeaea;
        }
    </style>

{% endblock %}
{% block content %}


    {% for message in app.flashes('info') %}
        <div class="alert alert-danger">
            {{ message }}
        </div>
    {% endfor %}
    <div id='tableView'>
        <table>
            {% for game in games %}
                <tr>
                    <td>{{ game.id }}</td>
                    <td>{{ game.name }}</td>

                    <td width="40%">
                        <div class="col-md-5 col-sm-4 col-xs-12">
                            <a href="{{ path('show_game', {'slug': game.slug}) }}"
                               class="btn btn-default">
                                {{ 'game.read.more' | trans }}
                                <i class="glyphicon glyphicon-chevron-right"></i>
                            </a>
                        </div>
                        {% if is_granted('ROLE_ADMIN') %}
                            <div class="col-md-3 col-sm-4 col-xs-12">
                                <a href="{{ path('edit_game',{'id':game.id}) }}"
                                   class="btn btn-default">
                                    {{ 'game.edit' | trans }}
                                </a>
                            </div>

                            {% if game.match is empty %}
                            <div class="col-md-4 col-sm-4 col-xs-12">
                                <form action="{{ url('delete_game', {id: game.id}) }}" method="post"
                                      data-confirmation="true" id="delete-form">
                                    <input type="hidden" name="token" value="{{ csrf_token('delete') }}"/>
                                    <button type="submit" class="btn btn-default btn-danger">
                                        {{ 'game.delete'|trans }}
                                    </button>
                                </form>
                            </div>
                            {% endif %}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

templates/game/show_game.html.twig
{% extends 'layout.html.twig' %}

{% trans_default_domain 'club' %}

{% set active = 'establishment' %}

{% block page_title %}
    {{ 'club.show.establishment' | trans }}
{% endblock %}

{% block content %}

    <div class="row">
        <!--colleft-->
        <div class="col-md-12 col-sm-12">
            <section id="single-product">
                <div class="container">
                    <div class="row">
                        <div class="col-md-5">
                            <div class="single-product-img">
                                {% if game.img is not empty %}
                                    <img alt="{{ game.name }}" src="{{ asset('images/game/'~game.img) }}" width="200">
                                {% endif %}
                            </div>
                        </div> <!-- End of /.col-md-5 -->
                        <div class="col-md-4">
                            <div class="block">
                                <div class="product-des">
                                    <h4>{{ game.name }}</h4>
                                    <p>{{ game.description | raw }}</p>
                                </div>    <!-- End of /.product-des -->
                            </div> <!-- End of /.block -->
                            {% for match in game.match %}
                                <a href="{{ path('show_match', {'id' : match.id}) }}">{{ match.name }}</a>
                            {% endfor %}
                        </div>
                    </div>    <!-- End of /.col-md-4 -->
                </div>    <!-- End of /.row -->
            </section> <!-- End of /.Single-product -->
        </div>
    </div>
{% endblock %}